cc_library(
    name = "strategies",
    srcs = [
        "do_nothing.h",
        "key_value.cpp",
        "key_value.h",
    ],
    hdrs = [
        "factory.h",
        "strategy.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/config",
        "@com_github_google_glog//:glog",
    ],
)
