cc_library(
    name = "strategies",
    srcs = [
        "do_nothing.h", 
        "key_value.h",
        "key_value.cpp"
    ],
    hdrs = ["strategy.h", "factory.h"],
    visibility = ["//visibility:public"],
    deps = ["@tomlplusplus//:main"],
)