cc_library(
    name = "config",
    srcs = [
        "builder.cpp",
        "config.cpp",
    ],
    hdrs = [
        "builder.h",
        "config.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@tomlplusplus//:main",
    ],
)
